var listaKML=
[
	{"id":"1", "nome":"Aeroporto","url": "http://b2allgae.appspot.com/kml/aeroporto.kmz"},
   {"id":"2", "nome":"Área de Estudo","url": "http://b2allgae.appspot.com/kml/area_de_estudo.kmz"},
	{"id":"3", "nome":"Área de Serviço Tempo","url": "http://b2allgae.appspot.com/kml/area_servico_tempo.kmz"},
  	{"id":"4", "nome":"Bancos e Caixas ATM","url": "http://b2allgae.appspot.com/kml/bancos_e_caixas_atm.kmz"},
  	{"id":"5", "nome":"Barcas","url": "http://b2allgae.appspot.com/kml/barcas.kmz"},
  	{"id":"6", "nome":"Bicicletários","url": "http://b2allgae.appspot.com/kml/bicicletarios.kmz"},
  	{"id":"7", "nome":"Bombeiros","url": "http://b2allgae.appspot.com/kml/bombeiros.kmz"},
  	{"id":"8", "nome":"Estação de Trem","url": "http://b2allgae.appspot.com/kml/estacao_de_trem.kmz"},
  	{"id":"9", "nome":"Estacionamentos","url": "http://b2allgae.appspot.com/kml/estacionamentos.kmz"},
  	{"id":"10", "nome":"Estações de Bicicletas","url": "http://b2allgae.appspot.com/kml/estacoes_de_bicicletas.kmz"},  
   {"id":"11", "nome":"Estações de Metrô","url": "http://b2allgae.appspot.com/kml/estacoes_metro.kmz"},
  	{"id":"12", "nome":"Fármacias","url": "http://b2allgae.appspot.com/kml/farmacias.kmz"},
  	{"id":"13", "nome":"Hoteis","url": "http://b2allgae.appspot.com/kml/hoteis.kmz"},
   {"id":"14", "nome":"Kernel Concentração Pontos Turísticos","url": "http://b2allgae.appspot.com/kml/kernel_concentracao_pontos_turisticos.kmz"},
	{"id":"15", "nome":"Polícia","url": "http://b2allgae.appspot.com/kml/policia.kmz"},
  	{"id":"16", "nome":"Ponto de Ônibus","url": "http://b2allgae.appspot.com/kml/pontos_de_onibus.kmz"},
  	{"id":"17", "nome":"Pontos Turísticos","url": "http://b2allgae.appspot.com/kml/pontos_turisticos.kmz"},
  	{"id":"18", "nome":"Pontos VLT","url": "http://b2allgae.appspot.com/kml/pontos_vlt.kmz"},
  	{"id":"19", "nome":"Potencial Turismo por Serviço de Apoio","url": "http://b2allgae.appspot.com/kml/potencial_turismo_por_servicos_de_apoio.kmz"},
  	{"id":"20", "nome":"Restaurantesj","url": "http://b2allgae.appspot.com/kml/restaurantes.kmz"},
  	{"id":"21", "nome":"Unidades de Saúde", "url": "http://b2allgae.appspot.com/kml/unidades_de_saude.kmz"},
];